---
# This file is part of secnix.com.
#
# secnix.com is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# secnix.com is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with secnix.com.  If not, see <http://www.gnu.org/licenses/>.

- name: Create /etc/nginx directories
  file:
    path: /etc/nginx/{{ item }}
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - sites-enabled
    - global

- name: Place the nginx configuration files
  copy: 
    src: "{{ item }}"
    dest: "/etc/nginx/{{ item }}"
  with_items:
    - nginx.conf
    - fastcgi_params

- name: Place the nginx global configuration files
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/global/{{ item }}"
  with_items:
    - restrictions.conf

- name: Place the sites-enabled configuration files
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
  with_items:
    - example.com

- name: Create the nginx log directory
  file:
    dest: /var/log/nginx
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Place the nginx systemd service file
  copy:
    src: secnix-nginx.service
    dest: /etc/systemd/system/secnix-nginx.service
    owner: root
    group: root
    mode: 0644
  register: svc_file

- name: update systemd
  command: systemctl daemon-reload
  when: svc_file.changed
  register: update_systemd

- name: Allow port 80/tcp from public
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: enable and start secnix-nginx
  service: 
    name: secnix-nginx.service
    state: restarted 
    enabled: yes
  when: update_systemd.changed
